### ISSUE TITLE
Modules are not loaded.

### ISSUE THREAD

**Issue by gio-salvador** [h-hirokawa/atom-autocomplete-ansible#15]
Only Directive are shown on the dropdown menu to choose from, Module is currently missing in my case.

MacOS 10.12.4
Atom 1.16.0 x64

**Comment by h-hirokawa** [comment]
@gio-salvador

The issue is caused by redesigned module document parser appeared in Ansible 2.3.0.
I will try to fix the issue ASAP.

**Comment by TUIteamup** [comment]
Great!
