### ISSUE TITLE
error immediately after installing

### ISSUE THREAD

**Issue by camilosantana** [h-hirokawa/atom-autocomplete-ansible#16]
to recreate, install the latest Atom. Install this package. Click on any .yml file. Get the following error.
```
autocomplete-python traceback output:
Command failed: /usr/local/bin/python "/Users/foo/.atom/packages/autocomplete-ansible/lib/parse_ansible.py"
Traceback (most recent call last):
  File "/Users/foo/.atom/packages/autocomplete-ansible/lib/parse_ansible.py", line 12, in <module>
    from ansible.utils import module_docs
ImportError: cannot import name module_docs
```

**Comment by h-hirokawa** [comment]
@camilosantana 
What version of ansible are you using?
Currently this plugin supports Ansible 2.0 ~ 2.3.

If you have the supported version, your ansible directory may be corrupted.
If so, please reinstall ansible and try again.

**Comment by camilosantana** [comment]
version of ansible - 2.4

ansible was installed via instructions at [docs.ansible.com]
(http://docs.ansible.com/ansible/intro_installation.html#latest-releases-on-mac-osx) for latest devel version via `sudo -H pip install git+git://github.com/ansible/ansible.git@devel`

i've removed ansible via `pip uninstall`
and installed ansible-2.3.0.0.

that seems to work

root cause: incompatible with ansible 2.4
suggestion: in README.md, change Requirements from `ansible >= 2.0` to `ansible 2.0 ~ 2.3`

thank you for your help.

**Comment by h-hirokawa** [comment]
@camilosantana 

Thank you for reporting!
I would add support for 2.4 before it become stable.
