### ISSUE TITLE
I get this every time I open ansible file in atom

### ISSUE THREAD

**Issue by wardcomm** [h-hirokawa/atom-autocomplete-ansible#17]
I get this every time I open ansible file in atom.
Is there a way fix it?
Command failed: undefined "C:\Users\jchadward\.atom\packages\autocomplete-ansible\lib/parse_ansible.py"
'undefined' is not recognized as an internal or external command,
operable program or batch file.

**Comment by h-hirokawa** [comment]
Unfortunately, Windows platform is not supported due to the limitation of Ansible.
I should add the obvious error messages for it.

**Comment by wardcomm** [comment]
Mr. Hirokawa,
I have ansible running under:
1.) Cygwin64 on windows 10 pro
2.) babun 32 bit on windows 10 pro
3.) Windows 10 subsystem(linux subsystem on windows10 pro )

reference three installed without any problem
https://www.jeffgeerling.com/blog/2017/using-ansible-through-windows-10s-subsystem-linux
.

I could help you with source if i new what was causing the problem.

Thank you,
J. Chad Wafd


*Thanks,*

*J. Chad Ward*
TEL   N/A
MOB   (803) 628-8267
jchadward@gmail.com
LinkedIn: www.linkedin.com/in/jchadward/en

**Comment by h-hirokawa** [comment]
Thank you for the reply.

In this case, Atom process seems running on Windows, not Linux.
And, even if you installed Ansible in linux subsystem (or virtual environment), Atom on Windows cannot communicate with Ansible on linux, as far as I know.
Anyway  I don't know much about Atom plugin on Windows, so if you know a good way, please let me know.

**Comment by wardcomm** [comment]
Where can we add more Ansible modules like these?
http://docs.ansible.com/ansible/list_of_all_modules.html

Can you document how to use atom-autocomplete-ansible (like how git the popup with modules to popup?

**Comment by oxie** [comment]
Guys how is it possible to install the autocomplete module for ansible on a windows 10 machine using atom. I`ve installed cygwin and installed all needed pythoin packages and ansible, but i was unable to manage to configure the ansible path to make it work.... any ideas ?

**Comment by pranaynanda** [comment]
How can I disable this message in atom if I can't use autocomplete-ansible on windows? 

> autocomplete-ansible traceback output:
> Command failed: C:\Program Files\Python35\python.exe "C:\Users\username\\.atom\packages\autocomplete-ansible\lib/parse_ansible.py"
> 'C:\Program' is not recognized as an internal or external command,
> operable program or batch file.

I've tried removing it from the configuration file but I still receive this message

**Comment by sunlove123** [comment]
@wardcomm : Hi i have installed Ansible in windows 7 through Cygwin64 and when i try cygwin64 command line ansible --version it gives the ansible version. if i do the same with script.bat and content "ansible --version" it says like "'ansible' is not recognized as an internal or external command". can u advice me how to make ansible active even in cmd?!! 
![ansible version](https://user-images.githubusercontent.com/25791116/37354982-2936b060-26e3-11e8-8f96-488acc9b5335.JPG)

**Comment by h-hirokawa** [comment]
@pranaynanda 
I fixed this path-related issue in v0.1.17, although it did not solve the fundamental problem on Windows.
