### ISSUE TITLE
please add ansible-advanced grammar

### ISSUE THREAD

**Issue by mmoole** [h-hirokawa/atom-autocomplete-ansible#29]
Please add .source.ansible-advanced to the supported grammars list since this is a new option now found in the language-ansible package.

https://github.com/h-hirokawa/atom-autocomplete-ansible/blob/f709ed7526b78f0fb7a2958cce7d3da01e7006bc/libs/provider.js#L14

**Comment by h-hirokawa** [comment]
@mmoole 
Thank you for reporting.
`.source.ansible-advanced` support is added in v0.1.18.
