### ISSUE TITLE
Failed on ansible 2.5

### ISSUE THREAD

**Issue by yodatak** [h-hirokawa/atom-autocomplete-ansible#32]
I got this on ansible 2.5

utocomplete-ansible traceback output:
Command failed: "/usr/bin/python" "/home/yodatak/.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
[DEPRECATION WARNING]: accelerate is kept for backwards compatibility but usage
 is discouraged. The module documentation details page may explain more about 
this rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: aos_asn_pool is kept for backwards compatibility but 
usage is discouraged. The module documentation details page may explain more 
about this rationale.. This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
[DEPRECATION WARNING]: aos_blueprint is kept for backwards compatibility but 
usage is discouraged. The module documentation details page may explain more 
about this rationale.. This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg

**Comment by yodatak** [comment]
And with deprecation_warnings=False i got autocomplete-ansible traceback output:
Command failed: "/usr/bin/python" "/home/yodatak/.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
Traceback (most recent call last):
  File "/home/yodatak/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 86, in <module>
    main()
  File "/home/yodatak/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 78, in main
    for lookup in lookup_loader.all():
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 435, in all
    module = self._load_module_source(name, path)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 346, in _load_module_source
    module = imp.load_source(full_name, path, module_file)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/lookup/aws_account_attribute.py", line 61, in <module>
    raise AnsibleError("The lookup aws_account_attribute requires boto3 and botocore.")
ansible.errors.AnsibleError: The lookup aws_account_attribute requires boto3 and botocore.

**Comment by h-hirokawa** [comment]
@yodatak 
For now, you need to install `boto3` and `botocore` to load [aws_account_attribute lookup plugin](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/aws_account_attribute.py).
I'm going to check if there is a way to skip the loading of certain plugins when the requirements are missing.

**Comment by h-hirokawa** [comment]
Related to #31.

**Comment by khelkun** [comment]
@h-hirokawa, my bad I should have figured that out
Everything's ok now, thanks!

**Comment by yodatak** [comment]
Yes it work with the install of boto3 and botocore #31

**Comment by h-hirokawa** [comment]
The problem has been solved, thanks to the effort of @zigarn.
