### ISSUE TITLE
Ansible does not auto complete modules

### ISSUE THREAD

**Issue by karimebiznext** [h-hirokawa/atom-autocomplete-ansible#39]
I do not get any modules like the gif you're showing ? the only auto complete i'm getting are the directives, am i missing something ?

**Comment by tgmedia-nz** [comment]
same here...
```
$ atom --version
Atom    : 1.30.0
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

$ python --version
Python 3.7.0
$ python2 --version
Python 2.7.15
```
autocomplete-ansible version 0.1.22
running arch:

```
lsb_release -a
LSB Version:	1.4
Distributor ID:	Antergos
Description:	Antergos Linux
Release:	rolling
```

**Comment by h-hirokawa** [comment]
@karimebiznext @tgmedia-nz 
I have released a version 0.1.24 which has compatibility with ansible >= 2.6.
Please try it.

**Comment by tgmedia-nz** [comment]
@h-hirokawa  - you're amazing! Cheers, all sorted for me.

**Comment by karimebiznext** [comment]
it's working now it needed an update , thank you sir :D
