### ISSUE TITLE
TypeError: on line 44, in parse_ansible.py after upgrading ansible

### ISSUE THREAD

**Issue by anthonyinfinity** [h-hirokawa/atom-autocomplete-ansible#50]
Hi guys, 

love this package on atom, saves me so mucht time. But after upgrading I am running into this error. Any ideas whats up?

`Command failed: "/.../.pyenv/shims/python" "/.../.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
Traceback (most recent call last):
  File "/.../.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 98, in <module>
    print(main())
  File "/.../.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 56, in main
    for module in get_module_list():
  File "/.../.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 44, in get_module_list
    founds = doc_cli.find_plugins(path, 'module')
TypeError: find_plugins() missing 1 required positional argument: 'ptype'`

**Comment by dnorthup-ums** [comment]
@anthonyinfinity What versions of Atom and Python are you using? Additionally, are you running this in a Python venv?

**Comment by dnorthup-ums** [comment]
@anthonyinfinity Additionally, are you running 2.9.13, 2.9.14, or some other version of Ansible?

**Comment by digifuchsi** [comment]
after upgrading to Ansible 2.10 I get the same error. Using Python 3.8 with Atom 1.51 on MacOS 10.15.7

**Comment by cgrigor** [comment]
+1 using MacOS 10.15.7, Python 3.7.5, Atom 1.5.1

**Comment by dnorthup-ums** [comment]
@digifuchsi & @cgrigor TY. Given the common denominator appears to Atom 1.5.1 and not Ansible 2.10.x I'm going to start there. Any other debug data is welcome.

**Comment by digifuchsi** [comment]
The error message I get is similar to the one above, but just for kicks:

`Command failed: "/usr/local/bin/python3" "/Users/cneugum/.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
Traceback (most recent call last):
  File "/Users/cneugum/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 98, in <module>
    print(main())
  File "/Users/cneugum/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 56, in main
    for module in get_module_list():
  File "/Users/cneugum/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 44, in get_module_list
    founds = doc_cli.find_plugins(path, 'module')
TypeError: find_plugins() missing 1 required positional argument: 'ptype'`

If you need any other information I am happy to provide it to you.

**Comment by dnorthup-ums** [comment]
@digifuchsi That clearly demonstrates that a Python venv isn't required. TY!

**Comment by k0ste** [comment]
![image](https://user-images.githubusercontent.com/7759548/96432164-b0dcfb80-122e-11eb-9b34-5cf96086a864.png)

Atom 1.52.0
Ansible 2.10.1
Python 3.8.6

**Comment by Chris-Softrams** [comment]
I'm having the same issue

**Comment by dnorthup-ums** [comment]
Looking to me like they changed the largely undocumented python interface, again. Red herring in #51 , this is definitely due to changes made in 2.10.x. Working on the fix...

**Comment by ebenezar-mccoy** [comment]
PR Created https://github.com/h-hirokawa/atom-autocomplete-ansible/pull/54

**Comment by shurrman** [comment]
same issue...

**Comment by dnorthup-ums** [comment]
Fixed with #56
