### ISSUE TITLE
autocomplete fails to load.

### ISSUE THREAD

**Issue by sandikata** [h-hirokawa/atom-autocomplete-ansible#51]
TypeError: find_plugins() missing 1 required positional argument: 'ptype'

ArchLinux

**Comment by dnorthup-ums** [comment]
@sandikata This looks like a duplicate of #50. Can you please tell me what versions of Python, Atom, and Ansible you are using, and if you are using a Python venv?

**Comment by sandikata** [comment]
Python 3.8 (Ubuntu 20.04) Latest Atom and ansible 2.9

**Comment by dnorthup-ums** [comment]
Ok, TY.

**Comment by dnorthup-ums** [comment]
@sandikata Work for this will continue on #50 .

**Comment by dnorthup-ums** [comment]
Fixed with #56
