### ISSUE TITLE
Does not find ansible installed by brew on macOS

### ISSUE THREAD

**Issue by walterrowe** [h-hirokawa/atom-autocomplete-ansible#59]
Despite having ansible installed and visible in my path, this plugin continues to insist I install ansible with pip.

<img width="464" alt="Screen Shot 2021-01-27 at 1 13 39 PM" src="https://user-images.githubusercontent.com/7131288/106035135-beade280-60a1-11eb-9a34-e4567dc89747.png">

The details below prove that ansible is installed and up-to-date.

```
% which ansible
/usr/local/bin/ansible

% brew info ansible
ansible: stable 2.10.6 (bottled), HEAD
Automate deployment, configuration, and upgrading
https://www.ansible.com/
/usr/local/Cellar/ansible/2.10.6 (37,746 files, 357.0MB) *
  Poured from bottle on 2021-01-27 at 13:08:49
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ansible.rb
License: GPL-3.0-or-later
==> Dependencies
Build: pkg-config ✔
Required: libyaml ✔, openssl@1.1 ✔, python@3.9 ✔
==> Options
--HEAD
	Install HEAD version

% which python
/usr/local/bin/python

% python --version
Python 3.9.1
```

The plugin should be more intelligent about discovering ansible.

**Comment by walterrowe** [comment]
Using this below (as indicated in the setting page of the plugin) seems to have cleared the error. Perhaps the plugin can find this automatically instead of requiring the user to constantly update it.

```
% head -1 /usr/local/bin/ansible
#!/usr/local/Cellar/ansible/2.10.6/libexec/bin/python3
```

<img width="729" alt="Screen Shot 2021-01-27 at 1 45 40 PM" src="https://user-images.githubusercontent.com/7131288/106038446-f6b72480-60a5-11eb-8a1e-2a2a8d768413.png">

**Comment by dnorthup-ums** [comment]
Did you have another version of Ansible installed somewhere else? Can you try capturing some debug logs?

**Comment by walterrowe** [comment]
I only had one version of ansible. I installed Python and Ansible using brew, and I run `brew upgrade` regularly to keep them updated. I do see two versions of Python - 3.8 and 3.9. Given the hint in the plugin to use `head -1 /usr/local/bin/ansible` to extract the proper python env, it would be useful if the plugin could simply do that each time Atom launches.

**Comment by walterrowe** [comment]
I just noticed that the Python reference above in my head output show it being inside the ansible Cellar. Hmmm.

**Comment by walterrowe** [comment]
I removed python@3.8 (`brew uninstall python@3.8`) just to make sure there can be no confusion.

Here is more information from my system if this helps:

```
% head -1 /usr/local/bin/ansible
#!/usr/local/Cellar/ansible/2.10.6/libexec/bin/python3

% cd /usr/local/Cellar/ansible/2.10.6/libexec/bin/

% ls -l python3
lrwxr-xr-x  1 wrowe  19191  84 Jan 26 18:25 python3 -> ../../../../../opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/python3.9

% cd ../../../../../opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/

% pwd
/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin

% ls -l
total 160
lrwxr-xr-x  1 wrowe  19191      8 Dec  7 17:33 2to3 -> 2to3-3.9
-rwxr-xr-x  1 wrowe  19191    168 Jan 13 09:38 2to3-3.9
-rwxr-xr-x  1 wrowe  19191    253 Jan 13 09:38 easy_install-3.9
lrwxr-xr-x  1 wrowe  19191      7 Dec  7 17:33 idle3 -> idle3.9
-rwxr-xr-x  1 wrowe  19191    166 Jan 13 09:38 idle3.9
-rwxr-xr-x  1 wrowe  19191    244 Jan 13 09:38 pip3
-rwxr-xr-x  1 wrowe  19191    244 Jan 13 09:38 pip3.9
lrwxr-xr-x  1 wrowe  19191      8 Dec  7 17:33 pydoc3 -> pydoc3.9
-rwxr-xr-x  1 wrowe  19191    151 Jan 13 09:38 pydoc3.9
lrwxr-xr-x  1 wrowe  19191      9 Dec  7 17:33 python3 -> python3.9
lrwxr-xr-x  1 wrowe  19191     16 Dec  7 17:33 python3-config -> python3.9-config
-rwxr-xr-x  1 wrowe  19191  50472 Jan 13 09:38 python3.9
-rwxr-xr-x  1 wrowe  19191   2110 Jan 13 09:38 python3.9-config

% brew info python3
python@3.9: stable 3.9.1 (bottled)
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python@3.9/3.9.1_6 (3,952 files, 65.6MB)
  Poured from bottle on 2021-01-13 at 09:38:11
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/python@3.9.rb
License: Python-2.0
==> Dependencies
Build: pkg-config ✔
Required: gdbm ✔, openssl@1.1 ✔, readline ✔, sqlite ✔, tcl-tk ✔, xz ✔
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.9/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.9/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
```

All of this tells me that ansible is configured to use the version of Python that Brew installed.

I am running macOS Catalina 10.15.7.

When the python path in the plugin matches the `head -1` path there are no errors.

**Comment by dnorthup-ums** [comment]
Can you enable the debug mode of this package (select the checkbox shown in the screenshot above) and gather debug logs via the developer tools, both with the manually-supplied path and without, as detailed in the manual?

https://flight-manual.atom.io/hacking-atom/sections/debugging/#check-for-errors-in-the-developer-tools

**Comment by walterrowe** [comment]
With no value provided for python:

```
Uncaught Error: Command failed: "/usr/bin/python" "/Users/wrowe/.atom/packages/autocomplete-ansible/libs/parse_ansible.py"
Traceback (most recent call last):
  File "/Users/wrowe/.atom/packages/autocomplete-ansible/libs/parse_ansible.py", line 9, in <module>
    from ansible.cli.doc import DocCLI
ImportError: No module named ansible.cli.doc

    at ChildProcess.exithandler (child_process.js:303)
    at ChildProcess.emit (events.js:200)
    at maybeClose (internal/child_process.js:1021)
    at Socket.<anonymous> (internal/child_process.js:430)
    at Socket.emit (events.js:200)
    at Pipe.<anonymous> (net.js:586)
```

When the correct value from `head -1 /usr/local/bin/ansible` I get no error.

**Comment by dnorthup-ums** [comment]
Thanks, I think you've uncovered the actual bug. Now to figure out what to do about it...

**Comment by walterrowe** [comment]
One thing to know .. /usr/bin/python on macOS is Python 2.7. 

```
% /usr/bin/python --version
Python 2.7.16
```

I have Python3 installed via Homebrew, but it does not create a `/usr/local/bin/python` symlink. I wonder what would happen if I created that? 

```
% echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

I have NO environment variables set for Python

**Comment by dnorthup-ums** [comment]
I thought homebrew did create that... (Perhaps it doesn't for the same reason that the system python is still 2.7.x?)
Does it install python 3.x with a `python3` alias?

**Comment by walterrowe** [comment]
Yes, python3 alias is created. Just no python so it doesn't conflict with macOS /usr/bin/python.

```
% which python3
/usr/local/bin/python3
```

**Comment by dnorthup-ums** [comment]
Cool, I'll see if I can make it prefer the python3 binary. That should work cross-platform.

**Comment by walterrowe** [comment]
Might even simply drop python2 support. It was sunset some time ago.

**Comment by dnorthup-ums** [comment]
What I was thinking is that if there aren't already there will eventually be things with only Python 3.x on them that only have /usr/bin/python and have dropped the instance at /usr/bin/python3.

**Comment by dnorthup-ums** [comment]
As for why I haven't outright dropped Python 2.x: Ansible still supports it (yuck). (At least last time I checked.)

**Comment by dnorthup-ums** [comment]
Note to self (and anyone else): Currently the binaries search is using the FIRST Python binary found, which doesn't always match the newest. I'm going to go eat something and get some sleep.

**Comment by walterrowe** [comment]
Any update on this?

**Comment by guard43ru** [comment]
After every ansible update (via homebrew), I must to edit the path manually.

Why not take the actual data from the output?
```
user@host % ansible --version
ansible 2.10.9
  config file = /Users/guard/Documents/ansible/server/ansible.cfg
  configured module search path = ['/Users/guard/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/3.4.0/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:33:11) [Clang 12.0.0 (clang-1200.0.32.29)]
```

**Comment by Moppiman** [comment]
Same on Debian 12.

**Comment by dnorthup-ums** [comment]
As Atom is discontinued this extension is also, alas I don't have the access needed to mark it as such.
