### ISSUE TITLE
Sorry for being dumb but how do you get do that secod auto fill bit?

### ISSUE THREAD

**Issue by sgpinkus** [h-hirokawa/atom-autocomplete-ansible#66]
In the video in README.md it shows auto filling required argument. But how do you trigger that? What does `module_name + a` mean? Please add more explain for dumb dumbs like me.

P.S. Thanks for the plugin!

**Comment by dnorthup-ums** [comment]
Literally append an "a" to the module name. The parser will then recognize that as "expand all snippets" and automatically provide some samples (from the Ansible documentation). I haven't looked into dealing with 2.11 and newer as much as I'd like so I can keep that working, but that will likely happen after I arrange to make mine the official fork and continue maintenance there.
